// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq5Te-TXo4XTg7aC57CCfddSTUpbsPCR8',
    appId: '1:929493329769:web:fb20159a875f6cded07ff8',
    messagingSenderId: '929493329769',
    projectId: 'android-bd782',
    authDomain: 'android-bd782.firebaseapp.com',
    storageBucket: 'android-bd782.firebasestorage.app',
    measurementId: 'G-FXLFLT1QYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg43ElAhPmtw4hacQnYInp0QkdsElfOPY',
    appId: '1:929493329769:android:b32f2f8f51c9cd45d07ff8',
    messagingSenderId: '929493329769',
    projectId: 'android-bd782',
    storageBucket: 'android-bd782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcVnj4xUHJjw8Xme6oKbsswVrKrzAPMg',
    appId: '1:929493329769:ios:da63c564d1cbefb2d07ff8',
    messagingSenderId: '929493329769',
    projectId: 'android-bd782',
    storageBucket: 'android-bd782.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcVnj4xUHJjw8Xme6oKbsswVrKrzAPMg',
    appId: '1:929493329769:ios:da63c564d1cbefb2d07ff8',
    messagingSenderId: '929493329769',
    projectId: 'android-bd782',
    storageBucket: 'android-bd782.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq5Te-TXo4XTg7aC57CCfddSTUpbsPCR8',
    appId: '1:929493329769:web:f62628637bc588b2d07ff8',
    messagingSenderId: '929493329769',
    projectId: 'android-bd782',
    authDomain: 'android-bd782.firebaseapp.com',
    storageBucket: 'android-bd782.firebasestorage.app',
    measurementId: 'G-0JSNN77NN0',
  );
}
